name: Trigger Other Workflows

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
    - cron: '0 * * * *'    # 9 minutes past every hour

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger testupdater
        if: github.event.schedule == '*/5 * * * *'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d '{"ref":"main"}' \
            https://api.github.com/repos/Marotzu/osu-track-refresher/actions/workflows/testupdater.yml/dispatches
      
      - name: Trigger autoupdate
        if: github.event.schedule == '9 * * * *'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d '{"ref":"main"}' \
            https://api.github.com/repos/Marotzu/osu-track-refresher/actions/workflows/autoupdate.yml/dispatches
